[directory]
truncate_to_repo = false
truncation_length = 5
truncation_symbol = "â€¦/"

[username]
show_always = true

[status]
disabled = false
map_symbol = true

[jobs]
symbol = "â–¸"
number_threshold = 1
symbol_threshold = 1

[time]
disabled = false
format = "[$time]($style) "
time_format = "%a %d%b%y %H:%M"
style = "yellow"

[cmd_duration]
min_time = 500
show_milliseconds = true
format = "[âŒ›ï¸$duration]($style) "

[rust]
disabled = true

[nix_shell]
format = "[$symbol$state( $name)]($style) "
symbol = "â„ï¸"
pure_msg = ""
impure_msg = "âœ–"

[env_var.DIRENV_DIR]
format = "[ğŸ“‚ENV]($style) "
style = "bold green"
